[tool.poetry]
name = "discord-bot"
version = "0.1.0"
description = ""
authors = ["Bulat Kurbanov <kurbanovbul@gmail.com>"]
readme = "README.md"
packages = [{include = "discord_bot"}]

[tool.poetry.dependencies]
python = "^3.11"
discord-py = "^2.4.0"
twitchapi = "^4.3.1"
pydantic = "^2.9.2"
pydantic-settings = "^2.6.1"
httpx = "^0.27.2"
icalendar = "^6.0.1"
pytz = "^2024.2"
mongojet = "^0.2.4"
taskiq = "^0.11.7"
taskiq-redis = "^1.0.2"
redis = {extras = ["hiredis"], version = "^5.2.0"}
fastapi = "^0.115.5"
authx = "^1.4.0"
httpx-oauth = "^0.15.1"
uvicorn = {extras = ["standard"], version = "^0.32.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
